export const data = [
  {
    id: 1,
    title: "You Don't Know JS Yet: Scope & Closures",
    Author: "Kyle Simpson ",
    img: "https://images2.imgbox.com/78/3a/aA9ImVxQ_o.jpg",
    genres: "Computer Science",
    pdf: "https://drive.google.com/file/d/1Zp2NOrGDtCGtazNJzwLy1hhVt2tghHzC/preview",
  },
  {
    id: 2,
    title: "HTML and CSS Design and Build Websites",
    Author: "Jon Duckett ",
    img: "https://images2.imgbox.com/68/11/RsygCJHn_o.jpg",
    genres: "Computer Science",
  },
  {
    id: 3,
    title: "Cracking the Coding Interview",
    Author: "Gayle Laakmann McDowell ",
    img: "https://images2.imgbox.com/a1/ac/C2u9KLoc_o.jpg",
    genres: "Computer Science",
  },
  {
    id: 4,
    title: "Data Structures and Algorithms Made Easy ",
    Author: "Narasimha Karumanchi ",
    img: "https://images2.imgbox.com/54/25/GBrI8T3p_o.jpg",
    genres: "Computer Science",
  },
  {
    id: 5,
    title: "Learn Python the Hard Way",
    Author: "Zed Shaw",
    img: "https://images2.imgbox.com/2b/89/S9teD06z_o.jpg",
    genres: "Computer Science",
  },
  {
    id: 6,
    title: "Head First Java",
    Author: "Kathy Sierra, Bert Bates",
    img: "https://images2.imgbox.com/0e/50/dsIyLlWP_o.jpg",
    genres: "Computer Science",
  },
];
